// packages-lit/src/button/index.ts
import {
  html,
  TemplateResult
} from "lit";
import {
  styleMap
} from "lit/directives/style-map.js";

import "./index.css";

export interface IButtonProps {
  primary?: boolean;
  backgroundColor?: string;
  size?: "small" | "medium" | "large";
  label: string;
  onClick?: () => void;
}

const Button = ({
  primary,
  backgroundColor,
  size,
  label,
  onClick
}: IButtonProps): TemplateResult => {
  const mode = primary ? "storybook-button--primary" : "storybook-button--secondary";

  return html`
    <button
      type="button"
      class=${[
    "storybook-button",
    `storybook-button--${size || "medium"}`,
    mode
  ].join(" ")}
      style=${styleMap({
    backgroundColor
  })}
      @click=${onClick}
    >
      ${label}
    </button>
  `;
};

export default Button;

// packages-vue/vue-hooks/stories/Button.vue
<script lang="ts" setup>
import "./button.css";

import {
  computed
} from "vue";

const props = withDefaults(defineProps<{

  /**
   * The label of the button
   */
  label: string,

  /**
   * Primary or secondary button
   */
  primary?: boolean,

  /**
   * Size of the button
   */
  size?: "small" | "medium" | "large",

  /**
   * Background color of the button
   */
  backgroundColor?: string,

}>(), {
  primary: false
});

const emit = defineEmits<{(e: "click", id: number): void;}>();

const classes = computed(() => ({
  "storybook-button": true,
  "storybook-button--primary": props.primary,
  "storybook-button--secondary": !props.primary,
  [`storybook-button--${props.size || "medium"}`]: true
}));

const style = computed(() => ({
  backgroundColor: props.backgroundColor
}));

const onClick = () => {
  emit("click", 1);
};

</script>
<template>
  <button type="button"
          :class="classes"
          :style="style"
          @click="onClick"
  >{{ label }} </button>
</template>
