// packages-vue/vue-element-plus-extra/src/rc-dialog/ui/rc/footer/index.vue
<script lang="ts" setup>

import {
  computed,
  isVNode
} from "vue";

import {
  isObject
} from "@mt-kit/utils";
import{
  ElSpace,
  ElButton
} from "element-plus";

import {
  usePropsOk,
  usePropsCancel,
  usePropsIsSubmit,
  usePropsFooterExtra,
  useHandleOnClose,
  useHandleOnSubmit,
  useStateLocked,
  ModelLockState
} from "../../../model";

const ok = usePropsOk();

const okButtonProps = computed(() => (isObject(ok.value) ? {
  ...ok.value
} : {
  label: ok.value
}));

const cancel = usePropsCancel();

const cancelButtonProps = computed(() => (isObject(cancel.value) ? {
  ...cancel.value
} : {
  label: cancel.value
}));

const isSubmit = usePropsIsSubmit();

const footerExtra = usePropsFooterExtra();

const handleClose = useHandleOnClose();

const handleOnSubmit = useHandleOnSubmit();

const locked = useStateLocked();

</script>
<template>
  <ElSpace>
    <component
      :is="footerExtra"
      v-if="isVNode(footerExtra)"
    />
    <template v-else>
      {{ footerExtra }}
    </template>

    <ElButton
      v-bind="cancelButtonProps"
      @click="handleClose"
    >
      {{ cancelButtonProps?.label || "关闭" }}
    </ElButton>

    <ElButton
      v-if="isSubmit"
      type="primary"
      :loading="locked === ModelLockState.LOADING"
      v-bind="okButtonProps"
      @click="handleOnSubmit"
    >
      {{ okButtonProps?.label || "提交" }}
    </ElButton>
  </ElSpace>
</template>

// packages-react/react-ant-design-extra/src/rc-dialog/ui/rc/footer/index.tsx
import React, {
  useMemo,
  MouseEvent
} from "react";

import {
  Button,
  Space
} from "antd";

import {
  useHandleOnClose,
  useHandleOnSubmit,
  useStateLocked,
  ModelLockState,
  usePropsFooterExtra,
  usePropsOk,
  usePropsCancel,
  usePropsIsSubmit
} from "../../../model";

export default function Footer(): React.ReactElement {
  const handleOnClose = useHandleOnClose();

  const handleOnSubmit = useHandleOnSubmit();

  const locked = useStateLocked();

  const footerExtra = usePropsFooterExtra();

  const ok = usePropsOk();

  const isSubmit = usePropsIsSubmit();

  const okButtonProps = useMemo(() => (typeof ok === "object" ? {
    ...ok,
    onClick: (event: MouseEvent<HTMLElement>) => {
      ok?.onClick?.(event);
      handleOnSubmit();
    }
  } : {
    label: ok
  }), [
    ok,
    handleOnSubmit
  ]);

  const cancel = usePropsCancel();

  const cancelButtonProps = useMemo(() => (typeof cancel === "object" ? {
    ...cancel,
    onClick: (event: MouseEvent<HTMLElement>) => {
      cancel?.onClick?.(event);
      handleOnClose();
    }
  } : {
    label: cancel
  }), [
    cancel,
    handleOnClose
  ]);

  return <Space>
    {footerExtra.map(button => (
      <React.Fragment key={button.key || Math.random()}>
        {button}
      </React.Fragment>
    ))}

    <Button onClick={handleOnClose}
      {...okButtonProps}>
      {typeof cancel === "string" ? cancel : cancel?.label || "关闭"}
    </Button>

    {isSubmit && <Button
      {...cancelButtonProps}
      loading={locked === ModelLockState.LOADING}
      onClick={handleOnSubmit}
      type="primary">
      {typeof ok === "string" ? ok : ok?.label || "提交"}
    </Button>}
  </Space>;
}
