// packages-react/react-ant-design-extra/stories/demo/index.tsx
import React, {
  useCallback
} from "react";

import {
  Button
} from "antd";

export default function Demo(): React.ReactElement {
  const handleClick = useCallback(() => {
    // eslint-disable-next-line no-console
    console.log("Click me");
  }, []);

  const handleTestClick = () => {
    // eslint-disable-next-line no-console
    console.log("React Ant Design Extra");
  };

  return <div>
    <p onClick={handleTestClick}>React Ant Design Extra</p>
    <Button onClick={handleClick}>Click me</Button>

  </div>;
}

// packages-vue/vue-components-el-extra/stories/demo/index.vue
<template>
  <div class="demo">
    <Button
      label="按钮"
      type="danger"
      :onClick="handleClick"
    />
    <br />
    <br />
    <br />
    <ButtonOps
      :items="[
        {label: '222'},
        {label: '33', isThrottle: true},
        '|',
        {label: '44'},
        {label: '55'},
        {label: '66'},
        {label: '77',onClick: handleClick},
        '|'
      ]"
    />
  </div>
</template>
<script lang="ts" setup>
import {
  Button,
  ButtonOps
} from "../../src";

const handleClick = (e: Event): void => {
  // eslint-disable-next-line no-console
  console.log(e);
};

</script>
<style scoped>
.demo {
  margin-top: 40px;
}
</style>
