// packages-react/react-ant-design-extra/stories/demo-open-dialog/content/index.tsx
import React from "react";

import {
  Form,
  Input
} from "antd";

import {
  useForm
} from "../../../src";

export default function Content(): React.ReactElement {
  const [
    form
  ] = useForm();

  return <Form
    autoComplete="off"
    form={form}
    initialValues={{
      remember: true
    }}
    labelCol={{
      span: 8
    }}
    name="basic"
    style={{
      maxWidth: 600
    }}
    wrapperCol={{
      span: 16
    }}>
    <Form.Item
      label="Username"
      name="username"
      rules={[
        {
          required: true,
          message: "Please input your username!"
        }
      ]}>
      <Input />
    </Form.Item>

    <Form.Item
      label="Password"
      name="password"
      rules={[
        {
          required: true,
          message: "Please input your password!"
        }
      ]}>
      <Input.Password />
    </Form.Item>
  </Form>;
}

// packages-vue/vue-element-plus-extra/stories/dialog/content/index.vue
<script lang="ts" setup>
import {
  ElForm,
  ElFormItem,
  ElInput
} from "element-plus";

import {
  useForm
} from "../../../src";

const [
  form

] = useForm<{
  name: string;
  password: string;
}>();

</script>

<template>
  <ElForm ref="form">
    <ElFormItem
      label="Username"
      name="name"
      required
    >
      <ElInput />
    </ElFormItem>
    <ElFormItem
      label="Password"
      name="password"
      required
    >
      <ElInput />
    </ElFormItem>
  </ElForm>
</template>
<style scoped>

</style>
