// packages-react/react-ant-design-extra/src/rc-dialog/ui/rc/drawer/index.tsx
import React from "react";

import {
  Drawer as AntDrawer

} from "antd";

import {
  usePropsContent,
  usePropsSize,
  useHandleOnClose,
  usePropsClassNameOnBody,
  usePropsBackdrop,
  usePropsClosable,
  usePropsEsc,
  usePropsZIndex,
  useStateOpen,
  transformWidthSize
} from "../../../model";
import Footer from "../footer";
import Header from "../header";

export default function Drawer(): React.ReactElement {
  const content = usePropsContent();

  const handleOnClose = useHandleOnClose();

  const size = usePropsSize();

  const open = useStateOpen();

  const classNameOnBody = usePropsClassNameOnBody();

  const backdrop = usePropsBackdrop();

  const closable = usePropsClosable();

  const esc = usePropsEsc();

  const zIndex = usePropsZIndex();

  return <AntDrawer
    closable={closable}
    destroyOnHidden
    footer={<Footer />}
    keyboard={esc}
    mask={backdrop}
    onClose={handleOnClose}
    open={open}
    rootClassName={classNameOnBody}
    title={<Header />}
    width={transformWidthSize(size)}
    zIndex={zIndex}>
    {content}
  </AntDrawer>;
}

// packages-vue/vue-element-plus-extra/src/rc-dialog/ui/rc/drawer/index.vue
<script lang="ts" setup>

import Footer from "../footer/index.vue";
import Header from "../header/index.vue";
import {
  isVNode
} from "vue";

import {
  ElDrawer
} from "element-plus";

import {
  transformWidthSize,
  usePropsContent,
  useStateOpen,
  useHandleOnClose,
  usePropsSize
} from "../../../model";

const open = useStateOpen();

const handleClose = useHandleOnClose();

const size = usePropsSize();

const content = usePropsContent();

</script>
<template>
  <ElDrawer
    v-model="open"
    :size="transformWidthSize(size)"
    @close="handleClose"
  >
    <template #header>
      <Header />
    </template>
    <component
      :is="content"
      v-if="isVNode(content)"
    />
    <template v-else>
      {{ content }}
    </template>
    <template #footer>
      <Footer />
    </template>
  </ElDrawer>
</template>
