// packages-vue/vue-element-plus-extra/src/rc-dialog/model/provider/index.vue
<script lang="ts" setup>
import Context from "../context/index.vue";
import Lifecycle from "../lifecycle/index.vue";
import {
  defineProps,
  ref,
  unref
} from "vue";

import reducer from "../reducer";
import {
  IDialogProps,
  IModelState,
  TModelAction
} from "../types";
import {
  getDefaultContextState
} from "../utils";

const {
  props
} = defineProps<{
  props: IDialogProps;
}>();

const state = ref<IModelState>(getDefaultContextState(props));

const dispatch = (action: TModelAction): void => {
  state.value = reducer(unref(state), action);

  // eslint-disable-next-line no-console
  console.log("Provider state", state.value);
};
</script>

<template>
  <Context
    :props="props"
    :dispatch="dispatch"
    :state="state"
  >
    <slot></slot>
    <Lifecycle />
  </Context>
</template>

// packages-react/react-ant-design-extra/src/rc-dialog/model/provider/index.tsx
import React, {
  useReducer
} from "react";

import Context from "../context";
import Lifecycle from "../lifecycle";
import reducer from "../reducer";
import {
  IModelProviderProps
} from "../types";
import {
  getDefaultContextState
} from "../util";

export default function Provider({
  children,
  props
}: IModelProviderProps): React.ReactNode {
  const [
    state,
    dispatch
  ] = useReducer(reducer, getDefaultContextState());

  return <Context.Provider value={{
    state,
    dispatch,
    props
  }}>
    {children}
    <Lifecycle />
  </Context.Provider>;
}
